#!/usr/bin/env bash
# Enable/disable launching the robot software (01_BRINGUP) automatically when
# the PC starts (Airi's decision: bringup by default, chosen yes/no in the
# setup web app; unblocked by cube_petit_ros#96 / PR #97).
#
# Enabled:  generates ~/.local/bin/cube_petit_bringup_launch.sh (a
#           self-contained launcher that sources ROS + the workspace and
#           bakes in the ROS env values -- NOT via .bashrc aliases, which
#           non-interactive shells never read) plus a systemd *user* service
#           ~/.config/systemd/user/cube-petit-bringup.service, then enables
#           it. The service is NOT started now: motors/sensors coming alive
#           mid-setup would be unsafe. It starts from the next boot.
# Disabled: disables (and stops) the service if it exists.
#
# Idempotent: re-running regenerates both files and re-applies enable/disable.
#
# Required env: AUTOSTART_ENABLED ("true"/"false")
# Required env when enabling: ROBOT_NAMESPACE
# Optional env: ROS_DOMAIN_ID (default 94), CUBE_PETIT_ROS_WS (default ~/ros),
#   FACE_COLOR (hex code, e.g. #ffa500 -- chosen in the setup wizard's
#   prereq step; baked into the generated launcher so autostart boots with
#   the user's choice instead of cube_petit_bringup's own hostname-derived
#   default. See cube_petit_bringup.launch.py's face_color argument.)
set -e

: "${AUTOSTART_ENABLED:?AUTOSTART_ENABLED is required (true/false)}"

SERVICE_NAME="cube-petit-bringup.service"
SERVICE_DIR="$HOME/.config/systemd/user"
SERVICE_PATH="$SERVICE_DIR/$SERVICE_NAME"
LAUNCHER="$HOME/.local/bin/cube_petit_bringup_launch.sh"
ROS_WS="${CUBE_PETIT_ROS_WS:-$HOME/ros}"
ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-94}"

# face_color:=<hex> only when the wizard has a chosen color to bake in --
# otherwise leave the launch command as-is and let
# cube_petit_bringup.launch.py fall back to its own default.
BRING_FACE_COLOR_ARG=""
if [ -n "${FACE_COLOR:-}" ]; then
  BRING_FACE_COLOR_ARG=" face_color:=${FACE_COLOR}"
fi

if [ "$AUTOSTART_ENABLED" != "true" ]; then
  echo -e '\e[1;31m == Disable robot autostart == \e[m'
  if [ -f "$SERVICE_PATH" ]; then
    # --now also stops a currently running instance; ignore failures so a
    # sandbox/headless environment (no user bus) still completes cleanly.
    systemctl --user disable --now "$SERVICE_NAME" 2>/dev/null \
      || echo "WARNING: could not talk to systemd --user; if the service is enabled, run: systemctl --user disable --now $SERVICE_NAME"
    echo "Autostart disabled."
  else
    echo "Autostart was not set up; nothing to disable."
  fi
  exit 0
fi

: "${ROBOT_NAMESPACE:?ROBOT_NAMESPACE is required when enabling autostart}"

echo -e '\e[1;31m == Enable robot autostart (bringup on boot) == \e[m'

mkdir -p "$(dirname "$LAUNCHER")" "$SERVICE_DIR"

# Baked-in env values: systemd user services do not read .bashrc, and the
# aliases there are interactive-only anyway. Keep in sync with the managed
# block written by setup_bashrc.bash.
cat >"$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by setup_autostart.bash -- launches the Cube Petit robot software
# at login. Regenerate by re-running the setup app's autostart step.
set -e

# Temporary opt-out, checked before anything else starts: killing the ros2
# launch process alone doesn't help (Restart=on-failure in the systemd unit
# just brings it back up 5s later). Toggle by editing ~/.config/cube_petit/env
# (create it if missing) and adding/uncommenting:
#   export CUBE_PETIT_AUTOSTART_DISABLE=1
# The same file is also sourced from ~/.bashrc (see setup_bashrc.bash) so an
# interactive shell sees the same variable -- but systemd user services never
# read .bashrc itself, hence this separate, explicit source here.
CUBE_PETIT_ENV_FILE="\$HOME/.config/cube_petit/env"
if [ -f "\$CUBE_PETIT_ENV_FILE" ]; then
  source "\$CUBE_PETIT_ENV_FILE"
fi
if [ -n "\${CUBE_PETIT_AUTOSTART_DISABLE:-}" ]; then
  echo "Autostart disabled via CUBE_PETIT_AUTOSTART_DISABLE in \$CUBE_PETIT_ENV_FILE"
  exit 0
fi

source /opt/ros/jazzy/setup.bash
if [ -f "$ROS_WS/install/setup.bash" ]; then
  source "$ROS_WS/install/setup.bash"
else
  echo "ERROR: $ROS_WS/install/setup.bash not found (is the workspace built?)" >&2
  exit 1
fi
export ROS_DOMAIN_ID=$ROS_DOMAIN_ID
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
export CYCLONEDDS_URI=file://\$HOME/cyclonedds.xml
exec ros2 launch cube_petit_bringup cube_petit_bringup.launch.py${BRING_FACE_COLOR_ARG}
EOF
chmod +x "$LAUNCHER"
echo "Wrote $LAUNCHER (namespace: $ROBOT_NAMESPACE, ROS_DOMAIN_ID: $ROS_DOMAIN_ID, workspace: $ROS_WS, face_color: ${FACE_COLOR:-<default>})"

cat >"$SERVICE_PATH" <<EOF
[Unit]
Description=Cube Petit robot bringup (01_BRINGUP) at boot
# Wait for the graphical session: the robot face and audio need the desktop.
After=graphical-session.target

[Service]
Type=simple
ExecStart=$LAUNCHER
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
echo "Wrote $SERVICE_PATH"

if systemctl --user daemon-reload 2>/dev/null \
    && systemctl --user enable "$SERVICE_NAME" 2>/dev/null; then
  echo "Enabled $SERVICE_NAME."
else
  echo "WARNING: could not talk to systemd --user in this environment."
  echo "Enable manually with: systemctl --user daemon-reload && systemctl --user enable $SERVICE_NAME"
fi

echo "Autostart is set up. It starts from the NEXT boot -- nothing is launched now"
echo "(starting motors/sensors in the middle of setup would be unsafe)."
